# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wavspdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=200)),
                ('result', models.BooleanField(default=False)),
            ],
        ),
    ]
