# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WAVSP_UI_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wavspdb',
            name='result',
            field=models.CharField(default='n', max_length=20),
        ),
    ]
