# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-29 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WAVSP_UI_app', '0002_auto_20180722_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='wavspdb',
            name='vuln_type',
            field=models.CharField(default='web', max_length=200),
        ),
    ]
