//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LocalUserManagement.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_LOCALUSERMANAGEMENT_DIALOG  102
#define IDR_MAINFRAME                   128
#define IDD_RESETPASSWORD_DIALOG        129
#define IDB_BACK                        133
#define IDB_FRONT                       134
#define IDD_PROPERTIES_DIALOG           135
#define IDD_ADD_DIALOG                  136
#define IDD_SINGLEADDUSER_DIALOG        137
#define IDD_MULTIPLEUSERADD_DIALOG      138
#define IDD_DOMAINUSERPROPERTIES_DIALOG 139
#define IDB_TITLE                       141
#define IDB_SEARCH                      142
#define IDB_SEARCHNEW                   143
#define IDB_BITMAP3                     145
#define IDC_CURSOR1                     146
#define IDB_STAR                        147
#define IDB_TITLE32                     148
#define IDB_BITMAP1                     150
#define IDB_BACKDISABLED                150
#define IDB_BITMAP2                     151
#define IDB_BACKENABLED                 151
#define IDB_BITMAP4                     152
#define IDB_FRONTDISABLED               152
#define IDB_BITMAP5                     153
#define IDB_FRONTENABLED                153
#define IDB_BITMAP6                     154
#define IDB_SEARCH1NEW                  154
#define IDB_BITMAP7                     156
#define IDB_HOME                        156
#define IDB_BITMAP8                     157
#define IDB_SEARCHSMALL                 157
#define IDD_csv                         159
#define IDC_COMBO1                      1000
#define IDC_BUTTON1                     1002
#define IDC_LIST2                       1003
#define IDC_EDIT1                       1004
#define IDC_EDIT2                       1005
#define IDC_EDIT3                       1006
#define IDC_GROUP1                      1007
#define IDC_LocalUsersButton            1008
#define IDC_ClearButton                 1010
#define IDC_DOMAINNAMELABEL             1011
#define IDC_USERNAMELABEL               1012
#define IDC_PASSWORDLABEL               1013
#define IDC_USERNAMELABEL2              1014
#define IDC_GROUP2                      1016
#define IDC_LIST1                       1017
#define IDC_PropertiesButton            1018
#define IDC_GROUP3                      1019
#define IDC_GROUP4                      1020
#define IDC_GROUP5                      1021
#define IDC_ResetPasswordButton         1022
#define IDC_AddButton                   1023
#define IDC_DeleteButton                1024
#define IDC_EnableButton                1025
#define IDC_DisableButton               1026
#define IDC_COMBO2                      1027
#define IDC_COMBO3                      1028
#define IDC_COMPUTERLABEL               1029
#define IDC_GROUPLABEL                  1030
#define IDC_GROUP6                      1031
#define IDC_PICTURECONTROL1             1032
#define IDC_NewPasswordLabel            1033
#define IDC_ConfirmPasswordLabel        1034
#define IDC_NewPasswordtextBox          1035
#define IDC_ConfirmPasswordtextBox      1036
#define IDC_CloseButton                 1037
#define IDC_OKButton                    1038
#define IDC_PICTURECONTROL2             1039
#define IDC_TAB1                        1040
#define IDC_DescriptionTextBox          1041
#define IDC_Close1Button                1042
#define IDC_FullNameLabel               1043
#define IDC_DescriptionLabel            1044
#define IDC_UserNameTextBox             1045
#define IDC_FullNameTextBox             1046
#define IDC_Apply1Button                1047
#define IDC_RADIO3                      1050
#define IDC_Apply2Button                1051
#define IDC_Close2Button                1052
#define IDC_Label1                      1053
#define IDC_Label2                      1054
#define IDC_Label3                      1055
#define IDC_Label4                      1056
#define IDC_Label5                      1057
#define IDC_Label6                      1058
#define IDC_Label7                      1059
#define IDC_RADIO1                      1060
#define IDC_RADIO2                      1061
#define IDC_CSVButton                   1062
#define IDC_GroupListView               1063
#define IDC_CreateButton                1064
#define IDC_TitleLabel                  1066
#define IDC_AddUserButton               1067
#define IDC_UserListgroupBox            1068
#define IDC_ComputerListgroupBox        1069
#define IDC_GroupListgroupBox           1070
#define IDC_UserListView                1071
#define IDC_ComputerListView            1072
#define IDC_PasswordTextBox             1074
#define IDC_OpenButton                  1077
#define IDC_FileNameTextBox             1078
#define IDC_SelectedFileLabel           1080
#define IDC_ImportButton                1081
#define IDC_InformationLabel            1082
#define IDC_StopButton                  1083
#define IDC_PROGRESS1                   1084
#define IDC_PROGRESS2                   1085
#define IDC_Stop2Button                 1086
#define IDC_Information2Label           1087
#define IDC_TotalComputersLabel         1088
#define IDC_SearchPictureBox            1089
#define IDC_SearchTextBox               1090
#define IDC_ReportLabel                 1092
#define IDC_ImportTextBox               1093
#define IDC_LinkLabel                   1097
#define IDC_StarPictureControl1         1098
#define IDC_StarPictureControl2         1099
#define IDC_Info1Label                  1105
#define IDC_Info2Label                  1106
#define IDC_Info3Label                  1107
#define IDC_Info4Label                  1108
#define IDC_PICTURECONTROL3             1109
#define IDC_PICTURECONTROL4             1110
#define IDC_HOMEPICTURECONTROL          1111
#define IDC_SelectAll1Button            1112
#define IDC_DeSelectAll1Button          1113
#define IDC_SelectAll2Button            1114
#define IDC_DeSelectAll2Button          1115
#define IDC_TotalUsersLabel             1116
#define IDC_TitleLabel2                 1117
#define IDC_Search2TextBox              1118
#define IDC_Search2PictureBox           1119
#define IDC_Title3Label                 1120
#define IDC_Browse                      1120
#define IDC_BUTTON2                     1121
#define Export                          1121
#define IDC_Import2                     1122
#define IDC_BUTTON3                     1142
#define IDC_Csvlabel                    1143
#define IDC_File                        1143
#define IDC_Csvlabel2                   1144
#define IDC_NOTE                        1145

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1146
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
